export const paths = {
  home: "/",
  trackOrder: "/track-order",
  seller: {
    login: "/seller/login",
    register: "/seller/register",
    onboarding: "/seller/onboarding",
    dashboard: "/seller/dashboard",
    store: "/seller/store",
    products: "/seller/products",
    productNew: "/seller/products/new",
    productEdit: (id: number | string) => `/seller/products/${id}/edit`,
    paymentMethods: "/seller/payment-methods",
    orders: "/seller/orders",
    orderDetail: (id: number | string) => `/seller/orders/${id}`,
    conversations: "/seller/conversations",
    conversationDetail: (id: number | string) => `/seller/conversations/${id}`,
  },
  admin: {
    login: "/admin/login",
    dashboard: "/admin/dashboard",
    stores: "/admin/stores",
    storeDetail: (id: number | string) => `/admin/stores/${id}`,
    reviews: "/admin/reviews",
    chats: "/admin/chats",
    orders: "/admin/orders",
    orderDetail: (id: number | string) => `/admin/orders/${id}`,
    chatDetail: (id: number | string) => `/admin/chats/${id}`,
    storeBadges: (id: number | string) => `/admin/stores/${id}/badges`,
  },
  customer: {
    login: "/customer/login",
    register: "/customer/register",
    recover: "/customer/recover",
    dashboard: "/customer/dashboard",
    profile: "/customer/profile",
    addresses: "/customer/addresses",
    orders: "/customer/orders",
    orderDetail: (id: number | string) => `/customer/orders/${id}`,
    complaints: "/customer/complaints",
    downloads: "/customer/downloads",
    reviews: "/customer/reviews",
    conversations: "/customer/conversations",
    conversationDetail: (id: number | string) => `/customer/conversations/${id}`,
    checkout: (slug: string) => `/store/${slug}/checkout`,
    storeProduct: (slug: string, productId: number | string) => `/store/${slug}/products/${productId}`,
  },
  store: (slug: string) => `/store/${slug}`,
} as const;
